title: Portifólio
author: Ana Carolina Gomes da Silva
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Portifólio pessoal profissional.

# social links
github_username:  https://github.com/lingsv # DO NOT include the @ character, or else the build will fail!

posts: https://github.com/lingsv/github_page_lingsv/tree/master/_posts

show_excerpts: false # set to false to remove excerpts on the homepage
