title: Portifólio de projetos e profissional
author: Ana Carolina Gomes da Silva
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Página com meu portifólio de projetos pessoais e profissionais.

# social links
github_username:  https://github.com/lingsv # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
