title: Portifólio de projetos e profissional
author: Ana Carolina Gomes da Silva
theme: architect
description: > # this means to ignore newlines until "baseurl:"
  Portifólio pessoal.

# social links
github_username:  https://github.com/lingsv # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
